CREATE TABLE leagues (
    leagueid SERIAL PRIMARY KEY,
    numteams int NOT NULL DEFAULT 12,
    numplayoffteams int NOT NULL DEFAULT 6,
	qbstart int NOT NULL DEFAULT 1,
	rbstart int NOT NULL DEFAULT 2,
	wrstart int NOT NULL DEFAULT 2,
	testart int NOT NULL DEFAULT 1,
	flexstart int NOT NULL DEFAULT 2,
	defstart int NOT NULL DEFAULT 1,
	kickerstart int NOT NULL DEFAULT 1,
	benchsize int NOT NULL DEFAULT 7,
    irsize int NOT NULL DEFAULT 3,
	qbmax int DEFAULT 4,
	rbmax int DEFAULT 8,
	wrmax int DEFAULT 8,
	temax int DEFAULT 4,
	defmax int DEFAULT 4,
	kickermax int DEFAULT 4,
	qbmax int DEFAULT 2,
	CONSTRAINT checkqb CHECK (qbmax >= qbstart),
    CONSTRAINT checkrb CHECK (rbmax >= rbstart),
    CONSTRAINT checkwr CHECK (wrmax >= wrstart),
    CONSTRAINT checkte CHECK (temax >= testart),
    CONSTRAINT checkdef CHECK (defmax >= defstart),
    CONSTRAINT checkkicker CHECK (kickermax >= kickerstart));